### PR TITLE
multiple terminals

### PR DESCRIPTION
**Pull request by firien**
allow multiple launched debug sessions - #46

### CODE REVIEW

**Comment by ko1** [comment]
I need to try to use what is difference.

**Comment by firien** [comment]
This maps debug sessions to terminals. It still creates terminals named "rdbg" but will create more than 1 if necessary. It will still reuse and open "rdbg" terminals too.

You can try it out by just launching the same debug task more than once. (vscode will warn you, but just proceed)
image

**Comment by firien** [comment]
rebased on `master`

**Comment by firien** [comment]
I also included some eslint fixes and changed terminal name to `Ruby Debug Terminal` ([e9ed034](https://github.com/ruby/vscode-rdbg/pull/56/commits/e9ed034cf6a3c8a9b1592c48216c9384dd8827b6)) to match the `JavaScript Debug Terminal` that ships with vscode. I can remove the name change if you wish.

**Comment by ko1** [comment]
Thank you!

**Pull request merged**
