### PR TITLE
Remove all common prefixes of multiple sockets

### PR DESCRIPTION
**Pull request by andyjeffries**
I want to use multiple sockets for my Rails app (one for a web process and one for a worker process), both being ready to use at any time. However, the problem is I can't easily see which socket to choose in VS Code. Due to MacOS's long paths, the "showQuickPick" method trims off the actual important part, so it ends up looking like this:

Screenshot 2023-09-13 at 10 22 25

The output of `rdbg --util=list-socks` is like this:

```
$ bundle exec rdbg --util=list-socks
/var/folders/gf/3z_681416nj3_zxgn2njdybm0000gn/T/ruby-debug-sock-501/ruby-debug-andy-32986
/var/folders/gf/3z_681416nj3_zxgn2njdybm0000gn/T/ruby-debug-sock-501/ruby-debug-andy-32998
```

The last parts after the trailing `/` are the important part, the filename and the PID, not all the folders stuff at the start.

This PR removes any common prefixes up to the last `/` and replaces them with `...` so the `showQuickPick` now looks like this:

Screenshot 2023-09-13 at 10 21 34

This is my first ever TypeScript code, it works well when using F5 and testing it, but if I've done something non-idiomatic, feel free to give suggestions and I'll fix them.

### CODE REVIEW

**Comment by andyjeffries** [comment]
@ko1 any update on getting this merged please?

**Comment by andyjeffries** [comment]
@ko1 @codergeek121 - could I get some eyes on this. Even without the "Session name" PR for the debug gem, this PR would be useful for those of us running multiple Ruby processes that we want to just generally be available for sudden jumping in to debugging.

**Comment by ko1** [comment]
Sorry for late response. Usually I couldn't check GH notification anymore... Please ping me @ko1 on ruby.social or somewhere else.

Anyway, I'm afraid to lost full path information because we can not recognize socket path issue (try to find in different directory) so I want to show dirname in `showQuickPick()` dialog like that:

image

Fortunately it checks only one directory so that it is enough just now. I'll make another PR with your co-author.

**Comment by ono-max** [comment]
Close this PR because https://github.com/ruby/vscode-rdbg/pull/406 solved this problem.

**Pull request closed without merging**
