### PR TITLE
Follow config option waitLaunchTime if defined when waiting for connection to port/socket

### PR DESCRIPTION
**Pull request by dmmatson**
I've found that sometimes 3 seconds is not long enough for `rdbg` to launch and for VSCode to connect to the socket. If I'm reading the code correctly, `waitLaunchTime` is only used when connecting to remote TCP/IP ports. Seems like we could also use the configuration to wait for local sockets, etc.

### CODE REVIEW

**Comment by ko1** [comment]
do you want to use this option?

From README

> With debug.gem 1.5.0 and later you may not need this configulation.

I don't touch the configuration more

**Comment by dmmatson** [comment]
I'm on debug 1.5.0 and I still see the error message from the extension saying that 3 seconds has elapsed and it couldn't connect.

**Comment by tristil** [comment]
I had timeout errors on 1.5.0. I opened a PR as a stopgap https://github.com/ruby/vscode-rdbg/pull/48/files, but this one is a better long-term solution. I think 30 seconds (or perhaps 10) is a better default though.

**Comment by dmmatson** [comment]
@ko1 done

**Pull request merged**
