### PR TITLE
icon proposal

### PR DESCRIPTION
**Pull request by firien**
I do not consider myself an artist, so I will take no offense if you reject this.
The blue marker inside is supposed to be the standard (ish) breakpoint icon.

image

### CODE REVIEW

**Comment by ko1** [comment]
Sorry, i couldn't understand how the proposed icon used on your screenshot. 8 line blue marker? (but it is different with icon.png)

**Comment by firien** [comment]
the proposed icon is just a generic ruby image with breakpoint inside it.
image

**Comment by firien** [comment]
I centered it a little better and rebased

**Comment by firien** [comment]
oh and the icon is only used in the extension gallery
image
and probably on the [marketplace website ](https://marketplace.visualstudio.com/items?itemName=KoichiSasada.vscode-rdbg)

**Comment by ko1** [comment]
Ah, I misunderstood it changes the editor's breakpoint lines (editor's face), but it changes the face of extension.

Let me check about it:

* how to treat the copyright of the icon? (I'm not sure the license about this kind of artwork)
* In future I want to prepare the icon of debug.gem and I think it should be similar. Do you mind to change it if it is available? (or making this icon as a debug.gem's logo is one idea)

**Comment by firien** [comment]
> * how to treat the copyright of the icon? (I'm not sure the license about this kind of artwork)

I just threw it together; I waive any copyright claims. 

> * In future I want to prepare the icon of debug.gem and I think it should be similar. Do you mind to change it if it is available? (or making this icon as a debug.gem's logo is one idea)

Feel free to use as you wish. I will close this PR (so it doesn't linger around) but I will keep [`firien:icon`](https://github.com/firien/vscode-rdbg/tree/icon) branch around if you want to use (or expand on) this icon in the future.

**Comment by ko1** [comment]
Thank you. I'll add your name in README as an author of icon.

**Review by ko1 — APPROVED** [review]

**Pull request merged**
