### PR TITLE
Bump typescript-eslint monorepo to 5.47.1 to deal with typescript-eslint warning

### PR DESCRIPTION
**Pull request by shibayu36**
I found that `@typescript-eslint/typescript-estree` displays a warning when running eslint like the following.

```
$ npm run lint

> vscode-rdbg@0.0.11 lint
> eslint src --ext ts

=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0

YOUR TYPESCRIPT VERSION: 4.6.3

Please only submit bug reports when using the officially supported version.

=============
```

This is because `@typescript-eslint/typescript-estree` used in the repository is old.  `@typescript-eslint/typescript-estree` is dependancy of @typescript-eslint/eslint-plugin.

So in this PullRequest, I update `@typescript-eslint/*` to deal with the above warnings.

### CODE REVIEW

**Comment by shibayu36** [comment]
I confirmed that the result of `npm run lint` is not changed.

```
$ npm run lint

> vscode-rdbg@0.0.11 lint
> eslint src --ext ts
```

**Comment by shibayu36** [comment]
See Also:

* https://github.com/typescript-eslint/typescript-eslint/issues/4614
* https://github.com/facebook/jest/pull/12557
    * a similar PullRequest to deal with the same warning

**Comment by ono-max** [comment]
Thank you! We need some time to review because it's hard to check package-lock.json. Sorry for waiting for you.

**Comment by ono-max** [comment]
@shibayu36 

Sorry, could you revert the change in package-lock.json? It's hard to review package-lock.json because of security.

**Comment by shibayu36** [comment]
OK, do you mean I should change only package.json and after that you are going to update package-lock.json by yourself?

**Comment by shibayu36** [comment]
@ono-max 
I fixed to only update package.json.  Please feel free if you have anything to want me to do 😄

**Comment by ono-max** [comment]
That's exactly what I said! Thank you for your patience!

**Review by ono-max — APPROVED** [review]

**Comment by shibayu36** [comment]
Thanks to merge!

**Pull request merged**
